<?php

/**
 * Created by PhpStorm.
 * User: nelson
 * Date: 02/06/18
 * Time: 02:10
 */

class ISS extends TemplateDeImpostoCondiconal
{
    function __construct($imposto = null)
    {
        parent::__construct($imposto);
    }

    public  function deveUsarOMaximo(Orcamento $Orcamento)
    {
        return $Orcamento->getValor() >300;
    }

    public  function taxacaoMinima(Orcamento $Orcamento)
    {
        return $Orcamento->getValor() * 0.1;
    }

    public  function taxacaoMaxima(Orcamento $Orcamento)
    {
        return $Orcamento->getValor() * 0.15;
    }

    public function calcula(Orcamento $Orcamento)
    {
        return parent::calcula($Orcamento); // TODO: Change the autogenerated stub
    }

}
